add-controllers
airkng/java-shareit pull request #1
Opened 2023-06-02 16:28 UTC by airkng

13 sprint: user and item functionals

2023-06-03 10:19 UTC, TomattmanYandex requested changes
Привет все коменты в коде, некоторые не дублировал, где одинаковые проблемы в разных сервисах
также 
Для репозиториев лучше сделать интерфейсы с публичными методами
и пакеты, обычно не делают подпакеты для конкретного функционала, это я в Item пакете писал, то же надо и для пользователей

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/ExceptionHandlers.java
> +package ru.practicum.shareit;
под обработчик ошибок следует сделать отдельный пакет, и поместить туда.
На основном уровне лучше почти ничего не хранить

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return mapper.toItemDto(itemService.get(itemId, userId));
маппинг лучше делать на уровне сервиса
т.е. сервис принимает и возвращает DTO

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        item.setId(itemId);
это тоже похоже на бизнес логику
можно сделать метод в сервисе, который будет принимать два параметра

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/exception/ItemNotFoundException.java
> +public class ItemNotFoundException extends RuntimeException {
лучше сделать просто ошибку NotFoundException, потому что она будет возникать не только с Item и поместить ее в отдельный пакет

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +package ru.practicum.shareit.item.service;
при текущем подходе с пакетами, обычно не создают подпакеты по функционалу, потому что по сути они будут иметь по одному классу
просто все классы, располагают в одном пакете, в текущем примере item 
На пакеты стоит разбить только если несколько классов можно сгрупировать по признаку, например есть несколько dto, или есть какая то подсущность (будет в следуюшем спринте)

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (userService.contains(item.getOwner().getId())) {
структуры с вложенностью обычно тяжело читаются, 
тут напрмиер если из юзер сервиса получать пользователя с таким id и его не будет, то он должен кинуть ошибку тоже, так что можно просто вызвать метод юзер сервиса на получение по id
userService.getByID(item.getOwner().getId()// если пользователь не найден, то упадет ошибка и выполнение дальше не пойдет
return itemRepository.create(item);

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (userService.contains(item.getOwner().getId())) {
аналогично, но можно еще проверить, реально ли пользователь владелец вещи

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +        item.setOwner(userRepository.get(item.getOwner().getId()).get());
это логика сервиса

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +        if (items.containsKey(item.getId())) {
эту логику тоже лучше подвигать в сервис

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +            if (!oldItem.getOwner().getId().equals(item.getOwner().getId())) {
это точно логика сервиса

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    public Optional<List<Item>> getAll() {
getAll не имеет смысл чтобы возвращал optional 
ведь если ничего не найдено, он может возвращать пустой лист
Optional стоит возвращать когда возвращаем один обьект

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return mapper.toUserDto(userService.get(userId));
маппер лучше на уровень сервиса подвигать

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userService.getAll().stream()
аналогично

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User user = mapper.toUser(userDto);
аналогично

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto replaceUser(@PathVariable("userId") final Integer userId,
почему replace а не update

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    @Getter
зачем геттер на эту мапу, она только для внутреннего хранения, все общение с ней должно быть через методы

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    public Optional<List<User>> getAll() {
optional с листами не возвращаем

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +        checkEmail(user.getEmail());
это проверка уровня сервиса

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    private final HashSet<String> emails = new HashSet<>();
зачем второй список с Email не проще ли пройтись по всем юзерам и проверить email

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    public User replace(final User userInfo, final Integer userId) {
почему replace а не update

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/exception/UserNotFoundException.java
> +public class UserNotFoundException extends RuntimeException {
То же что и с ItemNotExistException

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        Optional<User> user = userRepository.get(userId);
можно заменить весь метод на 
return userRepository.get(userId).orElseThrow(тут создание ошибки)

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        if (users.isEmpty()) {
по поводу этого писал в репозитории

2023-06-03 10:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        return userRepository.create(user);
вот тут следует делать проверку существует ли Email

2023-06-03 10:19 UTC, TomattmanYandex requested changes
Привет все коменты в коде, некоторые не дублировал, где одинаковые проблемы в разных сервисах
также 
Для репозиториев лучше сделать интерфейсы с публичными методами
и пакеты, обычно не делают подпакеты для конкретного функционала, это я в Item пакете писал, то же надо и для пользователей

2023-06-03 16:42 UTC, airkng commented on src/main/java/ru/practicum/shareit/ExceptionHandlers.java
> +package ru.practicum.shareit;
Тут как лучше сделать: создать папочку exceptions и туда все исключения перекинуть. А внутри нее создать папку handler и туда запихнуть обработчик?

2023-06-03 16:42 UTC, airkng commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return mapper.toItemDto(itemService.get(itemId, userId));
Поправим, шэф

2023-06-03 16:42 UTC, airkng commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        item.setId(itemId);
Сделано

2023-06-03 16:51 UTC, airkng commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    private final HashSet<String> emails = new HashSet<>();
да хочется чего-нибудь новенького, а то устал уже через стримы фильтровать

2023-06-03 16:51 UTC, airkng commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    public User replace(final User userInfo, final Integer userId) {
переделал

2023-06-03 16:58 UTC, airkng commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        Optional<User> user = userRepository.get(userId);
Точно, сделано!

2023-06-03 16:59 UTC, airkng commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    public Optional<List<User>> getAll() {
done

2023-06-04 13:37 UTC, airkng commented on src/main/java/ru/practicum/shareit/item/exception/ItemNotFoundException.java
> +public class ItemNotFoundException extends RuntimeException {
done

2023-06-04 16:59 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/ExceptionHandlers.java
> +package ru.practicum.shareit;
отличный вариант, а про то куда закинуть ошибки, если есть что то сугубо про пользователей, то можно и в пакет к пользователям, а ели есть общее что то, то тогда в exception

2023-06-04 17:11 UTC, TomattmanYandex approved these changes
Есть моменты которые стоит доделать, но они не сильно значительные, все равно к следующему спринту все придётся переделывать сильно, так что будешь делать следующее задание, обрати внимание на текущие коменты

2023-06-04 17:11 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        itemCreationDto.setUserId(userId);
Тут тоже спорный момент где это проставлять, тут или сделать чтобы метод в сервисе принимал на один параметр больше, но главное помни, что можно делать по разному)))

2023-06-04 17:11 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    public Optional<Item> get(final Integer itemId, final Integer userId) {
Кстати да, а зачем туть userId

2023-06-04 17:11 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        item.setOwner(userRepository.get(item.getOwner().getId()).get());
Плохой вариант, использовать Optional.get() без проверки на то пустой ли он, 
Лучше в начале получить пользователя, проверить что такой есть в базе, а потом уже делать что то дальше

2023-06-04 17:11 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        item.setOwner(userRepository.get(item.getOwner().getId()).get());
отбой тревоги увидел метод на один выше, но 
1) лучше получить это в начале, зачем выполнять какие то действия, если пользователь не найден
2) можно записать результат выполнения userService.get(item.getOwner().getId()); в переменную и использовать потом из переменной, а не делать два одинаковых запроса в базу

2023-06-04 17:11 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        increaseItemId();
а это логика репозитория

2023-06-04 17:11 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        item.setId(itemIdCount);
это логика репозитория

2023-06-04 17:11 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    private final HashSet<String> emails = new HashSet<>();
ну ок, не проблема

2023-06-05 07:25 UTC, airkng commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    public Optional<Item> get(final Integer itemId, final Integer userId) {
да на всякий случай. Он зачем-то в тестах присутствовал в качестве параметра, я его и впихнул на всякий. Вдруг в следующем тз пригодится

2023-06-05 07:27 UTC, airkng commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        item.setOwner(userRepository.get(item.getOwner().getId()).get());
Да, я тут полностью с тобой согласен, я так и хотел сделать. НО прикол в том, что из userService возвращается не User, а UserDto, и соответственно,  это разные сущности

2023-06-05 07:29 UTC, airkng commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        increaseItemId();
ахах, ты же писал, что это логика сервиса)))

2023-06-14 10:51 UTC, merged