feature: add-booking functional
airkng/java-shareit pull request #2
Opened 2023-06-16 22:11 UTC by airkng

Господи помилуй

2023-06-17 10:07 UTC, TomattmanYandex approved these changes
Привет, комменты в коде

2023-06-17 10:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private User owner;
а зачем нам тут владелец? 
кто является владельцем заказа? если владелец вещи, то он относится к вещи а не к заказу

2023-06-17 10:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAll(final Long userId, final String state, final Boolean isOwner) {
есть переменная IsOwner и много где условие, if(isOwner) else
есть способ получше сделать в  if(isOwner) {switch...} else {switch...}
но вообще есть вариант еще лучше и стоит переделать именно в него
сделать два отдельных метода getAll и getAllForOwner которые будут принимать только 2 параметра и 👍 1) избавляемся от лишних if
2) код становится понятнее за счет того, что есть два метода отвечающих за разные вещи, ну и не надо понимать что за boolean переменная

2023-06-17 10:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    private final HashMap<Long, Item> items = new HashMap<>();
это вообще стоит удалить 
весь класс

2023-06-17 10:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryDb.java
> +    List<Item> findByNameOrDescriptionAvailable(String text);
если делаешь метод с кастомным sql то можно назвать его попроще типа searchByText
или если в таком стиле как остальные методы findByNameOrDescriptionInAndAvailable

2023-06-17 10:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    .findByItemId(itemDto.getId(), Sort.by(Sort.Direction.DESC, "start"))
Почему бы не сделать отдельный запрос, который будет искать только один букинг следуюий и предыдущий,
представь что есть очень популярный предмет, который в приложении уже годы, и его заказывают часто,
у него будет очень много букингов, и для того чтобы получить только один из них, мы будем получать все, а потом проходить все, но при этом для того чтобы найти следующий, мы будем делать все то же самое

2023-06-17 10:08 UTC, TomattmanYandex requested changes
хз как исправить случайно нажатый апрув

2023-06-17 13:40 UTC, airkng commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAll(final Long userId, final String state, final Boolean isOwner) {
я думал над всеми вариантами, хотел укоротить код + логика в принципе тут понятная

2023-06-17 13:42 UTC, airkng commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryDb.java
> +    List<Item> findByNameOrDescriptionAvailable(String text);
done

2023-06-17 13:42 UTC, airkng commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    private final HashMap<Long, Item> items = new HashMap<>();
done

2023-06-17 13:50 UTC, airkng commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAll(final Long userId, final String state, final Boolean isOwner) {
done

2023-06-17 13:59 UTC, airkng commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private User owner;
Да, это владелец вещи. Я его сюда закинул для простоты использования. Переделаю

2023-06-17 14:00 UTC, airkng commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private User owner;
done

2023-06-17 14:54 UTC, airkng commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    .findByItemId(itemDto.getId(), Sort.by(Sort.Direction.DESC, "start"))
done

2023-06-18 10:15 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAll(final Long userId, final String state, final Boolean isOwner) {
но лучше было бы сделать два отдельных метода

2023-06-18 10:15 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    .findByItemId(itemDto.getId(), Sort.by(Sort.Direction.DESC, "start"))
и тут тоже, лучше бы сделать вместо сохранения в переменную, отдельный метод поиска

2023-06-18 10:16 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    .findByItemId(itemDto.getId(), Sort.by(Sort.Direction.DESC, "start"))
меньше память бы забивалась

2023-06-18 10:16 UTC, TomattmanYandex approved these changes
Принято

2023-06-19 09:49 UTC, airkng commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAll(final Long userId, final String state, final Boolean isOwner) {
ни хотю

2023-06-27 13:50 UTC, merged