Add item requests
airkng/java-shareit pull request #3
Opened 2023-07-02 19:14 UTC by airkng

2023-07-03 08:36 UTC, TomattmanYandex requested changes
Комменты как обычно в коде
плюс доп моменты
1) все тесты которые используют базу должны выполняться на тестовой базе
2)не хватает юнит тестов (тест где мы мокаем зависимости и проверяем только внутрянку метода)
3) хорошая структура теста
обычно хорошие тесты состоят из трех частей, их часто даже коментами отделяют
given when then
void getBokingByIdTest(){
//given
тут создаем данные что нужны для теста
//when 
вызываем сам тестируемы метод
//then
проводим всякие проверки
}
при такой структуре есть хорошее разделение метода на части

2023-07-03 08:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAll(final Long userId, final String state, final Boolean isOwner, final Integer from, final Integer size) {
а я в предыдущем спринте не делал замечание что лучше сделать два метода, один для owner второй для всех?

2023-07-03 08:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Page<Booking> bookings = null; //TODO: возможно убрать инициализацию
чтобы вот это не делать, можно было бы
прям в мапере сделать метод который принимал бы список, и внутри себ яделал  то же что и последняя строчка метода
а в строчках 114, 117 и т.д. сделать 
return mapper.map(bookingRepository.findAllByItemOwnerId(userId, pages));
return bookingRepository.findAllByItemOwnerId(userId, pages);

2023-07-03 08:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                            @RequestParam(defaultValue = "10") @PositiveOrZero final int size) {
уверен что ут эта аннотация подойдет для валидации, что убдет если там будет 0
чувствую что надо написать на это тест)))

2023-07-03 08:36 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Pageable pages = PageRequest.of(from == 0 ? 0 : from / size, size, sort);
момент не то чтобы важный, но больше про удобство, 
у тебя есть создание pageble с внутренней логикой, и вдруг приходит запрос на изменение
(не самый вероятный вариант) для каждой четной страницы надо показывать аткже что ыбло на предыдущей(еще больше усложняем логику) ну или вариант реалистичнее,в первом параметре приходит сразу номер страницы, и ничего считать не надо
С текущим подходи, прийдется идти по коду, и в каждом месте, где создается Pagable - менять, а если сделать утильный класс, с методом, который будет создавать этот pagable  и везде использовать его, то получается так, что изменить прийдется только в одном месте

2023-07-03 08:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingCreationDtoTest.java
> +public class BookingCreationDtoTest {
строчка пустая выше, зачем?

2023-07-03 08:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper objectMapper;
модификатор доступа

2023-07-03 08:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    public void testAddBooking_InvalidUserId_ShouldReturnNotFoundStatus() throws Exception {
зачем в имени метода test  то что это тест мы можем понять по формату имени и по аннотации @Test на строку выше
вот первый тест поименован отлично

2023-07-03 08:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    UserCreationDto userDto1 = UserCreationDto.builder().email("user1@email.com").name("user1").build();
модификаторы доступа

2023-07-03 08:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        System.out.println("RESULT!!!!!!!!!!!!!");
System.out.println удаляем нафиг и не используем, 
хочется что то вывести используем логи

2023-07-03 08:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        BookingCreationDto bookingEntryDto = BookingCreationDto.builder().itemId(item1.getId())
хорошая структура такого теста была бы такая,
создали дто вызвали метод который тестим, потом из репозитория получили созданный объект (по Id из вернувшейся dto) и сравнили поля

2023-07-03 08:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        assertEquals(bookingEntryDto.getStart(), actual.getStart());
С такой проверкой обьект может не дойти до базы, но все равнотест пройдет

2023-07-03 08:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        assertEquals(2, testBookings1.size());
это закрывает проблему из предыдущего коммента, но все равно, лучше сделать как в первом коменте

2023-07-03 08:36 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    void addBooking_InvalidUserId_shouldReturnNotFound() {
это было бы отличным юнит тестом

2023-07-03 08:55 UTC, airkng commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAll(final Long userId, final String state, final Boolean isOwner, final Integer from, final Integer size) {
Да, мы пришли к выводу, что можно и так и так. Отдельный метод конечно лучше, но тестировать и в принципе использовать удобнее в рамках одного метода

2023-07-03 09:23 UTC, airkng commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Page<Booking> bookings = null; //TODO: возможно убрать инициализацию
классная штука, но я не хочу писать потом к этому тесты)))))

2023-07-03 09:28 UTC, airkng commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Pageable pages = PageRequest.of(from == 0 ? 0 : from / size, size, sort);
Очень хороший приемчик, возьму на заметку

2023-07-04 08:06 UTC, TomattmanYandex reviewed
некоторые моменты не пофикшены, например некоторые валидации, но принято

2023-07-04 08:06 UTC, TomattmanYandex approved these changes

2023-07-10 15:17 UTC, merged